apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  source:
    repoURL:  https://github.com/JuanPabloSGU/kyverno-demo.git   
    path: k8s/kyverno/
    targetRevision: HEAD
    helm:
      valueFiles:
        - sandbox/values.yaml
  project: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - respectIgnoreDifferences=true

